language: node_js
dist: trusty
sudo: false
node_js:
  - "10"
cache: yarn
branches:
  except:
    - /^v\d/
install:
  - yarn install
script:
  - yarn run lint
  # - yarn run test
  - yarn run test:integration
before_deploy:
  - >
    if [ "${TRAVIS_BRANCH}" = "develop" ]; then
      yarn run build;
    elif [ "${TRAVIS_BRANCH}" = "master" ]; then
      yarn run build:production;
    fi
deploy:
  - provider: firebase
    skip_cleanup: true
    project: gdg-es-develop
    on:
      branch: develop
  - provider: firebase
    skip_cleanup: true
    project: gdg-es
    on:
      branch: master
env:
  global:
    secure: YBQ/zuofUTM5iYNlNlHmAYoQu1jMrJITVGwmicZtW+YnL011V1tiMv7kez0tyBY5u5YAw/nPHnojVRRyEhYTISHq64dRrgfZSSipo2WWuA33V+Dc4pnNQXKYbuLEDr2GpTUQBHylTKBIHM5Qrm1tfLLjgSOQ6QEV7bokErB4St3Fv3oa3MnH6N17sYvyxAUu+DZu7ovj2lFLLUDb0SMINbGIbdrVsaatRwti4DfUNUWzImLtmdTIPjYWfcDlHbUHCYuzWvmo6eWWEU0IJXbW8BtQsRGnNo9RWunHWZjz6u0/e9HxLDigkRsEWXx2qSLFT6LoUeypOXQC0aCQe/38vMqyWGiPsTB2Orw1iPIUxalQ3ETC9fcUjtuBMmLeplEAvEN702WCSJwlK5ezGhzWmWrrbUsEC9vmGl3PCQnt86w6AIiPnFs3CtAP1kQjpbprSa3+Ok32uHfVfryfkY9MViwKCkQ6tgtiZoYNgVaCQN5QqdNjKy+xoPBlE3wgwIqmUWY0LdPpmoA8K7hoIW1zF/VKKQxFGiCKPhGP/jMVusipZY21JIcYg7+5h+qKjk26TmxSox2TvlexYNexP1cvVISOGzowqKHJUuO0IAaxvTHX//0sgs10T5oNJioyj4nc8x0WXnARKpuNaUVMjpupiDsy74WyPFOhsLtN5u2ShIQ=
